### ISSUE TITLE
I want to contribute 

### ISSUE THREAD

**Issue by afhorton** [ukraine/jobBanksCanada#1]
Hi George,

I came across a post about your project (please see below).  I am an expert in JavaScript as well as an ESL teacher.

I am interested in contributing to the project posted about.

Here is the post:

Що нового в нашому додатку для імігрантів для вивчення та вдосконалення анг чи фр мови? Нагадаю, це як дуо лінго, тільки повністю на ШІ і на 100% персоналізоване
-
🔊 Зробили модуль, який генерує справжні голосові діалоги по обраній темі. Наприклад, якщо хочу стати хірургом в новій країні, я буду чути все про це, а не "я хотіти хліб йти в магазин" знову і знову. Штука також тренує слух
-
🦜Третій модуль, над яким працюємо, розуміє що ти говориш, пояснює які помилки допущені, підказує що треба поправити і чому (граматика, тощо)
-
📕 Один з перших модулів генерував навчальний з покращення словникового запасу по обраній користувачем темі. Фокусується на помилках впродовж навчання
-
👉 Написав, бо хочу поділитися прогресом, знайти нових бета користувачів, JavaScript розробників. Зараз шукаємо тих, кому це просто цікаво і хто має вільних кілька годин щодня

**Comment by ukraine** [comment]
Hi. Please get in touch with me through facebook
